### ISSUE TITLE
Font manifests (like `package.json`, but for fonts)

### ISSUE THREAD

**Issue by tecc** [tecc/fontpm#6]
It could be a useful feature to be able to create some kind of font manifest and then other users can use fontpm to get all required fonts.
I'm thinking something similar to this:
```toml
# define the fontspecs like you would pass them to the command line
fonts = ["roboto", "noto-sans"]
# and then other options too, like the new css generation
generate_css = true
out_dir = "assets/fonts"
````
